name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci
      
    - name: Install API dependencies
      run: |
        cd api
        npm ci
        
    - name: Install UI dependencies
      run: |
        cd ui
        npm ci
        
    - name: Lint root
      run: npm run lint
      
    - name: Lint API
      run: |
        cd api
        npm run lint
        
    - name: Lint UI
      run: |
        cd ui
        npm run lint
        
    - name: Test root
      run: npm run test
      
    - name: Test API
      run: |
        cd api
        npm run test
        
    - name: Test UI
      run: |
        cd ui
        npm run test
        
    - name: Build API
      run: |
        cd api
        npm run build
        
    - name: Build UI
      run: |
        cd ui
        npm run build

  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd api && npm ci
        cd ../ui && npm ci
        
    - name: TypeScript check (root)
      run: npx tsc --noEmit
      
    - name: TypeScript check (API)
      run: |
        cd api
        npx tsc --noEmit
        
    - name: TypeScript check (UI)
      run: |
        cd ui
        npx tsc --noEmit
